# -*- coding: utf-8 -*-
"""miniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12U5oFL84M99XYj30QxRjDD8of03FBqee
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("myExpenses1.csv")
df

df.describe()

df.isna().sum()

df.dropna()

# total amount spended
print(df.Amount.sum())

df.Item.unique()

print("Total Expense:", df['Amount'].sum())
print("Average Expense:", df['Amount'].mean())
print("Median Expense:", df['Amount'].median())
print("Highest Single Expense:", df['Amount'].max())
print("Lowest Expense:", df['Amount'].min())

food_items = ['chai','chai with snaks','juice','pizza','biryani','coffee']
food_expense = df[df['Item'].isin(food_items)]['Amount'].sum()

print("Food-related expense:", food_expense)
print("Percentage of total expense:", round(food_expense/df['Amount'].sum()*100,2), "%")

#Most Frequently Purchased Items

item_count = df['Item'].value_counts().head(10)

plt.figure(figsize=(8,4))
sns.barplot(x=item_count.index, y=item_count.values)
plt.xticks(rotation=45)
plt.title("Most Frequently Purchased Items")
plt.show()

# top 10 items based on spending
sns.barplot(x=df1.Item, y=df1.Amount,data=df1)

df2 = df.groupby("Date").sum().sort_values(by="Amount",ascending=False).head(5)
df2 = df2.reset_index()

# on which dates spends more
sns.barplot(x=df2.Date, y=df2.Amount, data=df2)

df3 = df.groupby("day").sum().sort_values(by="Amount",ascending=False)
df3 = df3.reset_index()

# which day spends more
colors = sns.color_palette('bright')[0:5]
plt.pie(data=df3,labels=df3.day,colors=colors,x="Amount",autopct='%.0f%%')
plt.show()

df.groupby('Category')['Amount'].sum()

#spending by categry
plt.pie(labels=df.groupby('Category')['Amount'].sum().index,
       x=df.groupby('Category')['Amount'].sum().values,autopct='%.0f%%')
plt.show()

# which time spending more
df.groupby("Time")['Amount'].sum().plot()

# spending date wise
import plotly.express as px
px.line(x=df.groupby('Date')['Amount'].sum().sort_index().index,
        y=df.groupby('Date')['Amount'].sum().values)

